### ISSUE TITLE
修改源码后，怎么打包成exe文件？

### ISSUE THREAD

**Issue by ffrankfeng** [kookob/smpic#4]

**Comment by kookob** [comment]
如果是安装版的ahk，右键点击有个Compile Script菜单，点击就自动生成exe了。
如果需要定制一些图标：在安装目录下面：Compiler\Ahk2Exe.exe

**Comment by ffrankfeng** [comment]
> 如果是安装版的ahk，右键点击有个Compile Script菜单，点击就自动生成exe了。
> 如果需要定制一些图标：在安装目录下面：Compiler\Ahk2Exe.exe
只编译smpic.ahk文件，运行报错：Could not extract script from EXE，怎么解决呢

**Comment by kookob** [comment]
你这是反编译exe，不是打包。

fengf96 <notifications@github.com> 于2020年3月5日周四 上午9:51写道：
