### ISSUE TITLE
用不了，能否修复一下

### ISSUE THREAD

**Issue by sanmaodo** [kookob/smpic#5]
总是提示，上传失败，请稍候再试！

**Comment by kookob** [comment]
用的免费图床吗？sm官方api可能有变更过，需要更新下。

**Comment by sanmaodo** [comment]
期待！

**Comment by kookob** [comment]
@sanmaodo 你好，新版本已经上传了。
因为sm.ms 的最新api，只允许登录用户上传，所以需要你自己登录后台，生成自己的Secret Token，然后在配置文件里面替换，就可以使用了。
具体可以看下readme和smpic.ini的说明。

**Comment by sanmaodo** [comment]
@kookob 一切恢复正常，感谢！
